### PR TITLE
[02/02/2024] Extract docstrings from Javascript files

### LINKED ISSUE #2: [01/-2/2024] Extract doc strings from Javascript files
The docstrings in JSDoc syntax should be extracted from the javascript files. These docstrings may include categories to group documentation into different sections. i.e. (you may have a set of files with closely related functionality, and you want the generated documentation to have its separate category or section.)

Parent issue #1

While extracting the docstrings, make sure to account for docstrings generated and assigned to a particular category even if the docstrings are located in different files

- [x] Add logic to extract docstring
- [x] Extract docstring from multiple files

### PR DESCRIPTION
**Pull request by RealRichi3**
This PR aims to extract the JSDoc docstrings from javascript files, temporarily it'll be written to txt file to confirm it works as expected. Later on these docstrings will be written to quarto markdown file.

Fixes #2

### TODO
- [x] Extract docstrings from files
- [x] Write docs to txt file

### CODE REVIEW

**Comment by BatoolMM** [comment]
Thank you @RealRichi3 let me know when you want me to review!

**Comment by RealRichi3** [comment]
@BatoolMM, I've been able to extract the Jsdoc comments and write them to file, although, haven't set it up for multiple files, and i'll have to work on writing all neccesssary data completely, i can work on that on another PR, i think this is okay to merge to dev

**Comment by BatoolMM** [comment]
This looks fantastic, thank you so much - do you think you can add some comments in the functions/scripts you created? just to make it easier to follow your thoughts on creating the scripts.

**Review by BatoolMM — APPROVED** [review]

**Comment by RealRichi3** [comment]
> This looks fantastic, thank you so much - do you think you can add some comments in the functions/scripts you created? just to make it easier to follow your thoughts on creating the scripts.

Sure, I'll include the comments

**Pull request merged**
